In [1]:
import torch 
torch.__version__

'2.2.1+cu118'

In [2]:
#Creating scalar value 
scalar  = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim#dimension of scalar is 0 

0

In [4]:
#retriving number from tensor 
scalar.item()

7

In [5]:
#creating a vector
vector = torch.tensor([7 , 7])
print(vector) 


tensor([7, 7])


In [6]:
vector.ndim 

1

In [7]:
vector.shape #this gives the number of elements in  vector

torch.Size([2])

In [8]:
#creating matrix 
matrix = torch.tensor([[7 , 8] ,
                       [5  , 6]])
matrix , matrix.ndim , matrix.shape

(tensor([[7, 8],
         [5, 6]]),
 2,
 torch.Size([2, 2]))

In [9]:
tensor  = torch.tensor([[[1 ,2,3] , 
                         [4 ,5,6] , 
                         [7,8,9]]])
tensor.ndim , tensor , tensor.shape

(3,
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [10]:
#creating random tensor of size (3,4)
random_tensor = torch.rand(size = (3 , 4))
random_tensor , random_tensor.dtype

(tensor([[0.5269, 0.8831, 0.5768, 0.5399],
         [0.9018, 0.8896, 0.4966, 0.2340],
         [0.0216, 0.5360, 0.1779, 0.2339]]),
 torch.float32)

In [11]:
random_image_tensor = torch.rand(size = (224,224,3))
random_image_tensor.shape , random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [12]:
#creating zeros and ones 
zeros = torch.zeros(size = (3 , 4))
zeros , zeros.dtype , zeros.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32,
 2)

In [13]:
ones = torch.ones(size = (3 , 4))
ones , ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [14]:
#creating range and tesnors 
zero_to_ten = torch.arange(start=0 , end = 10 , step = 2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [15]:
zero_to_ten.dtype , zero_to_ten.device

(torch.int64, device(type='cpu'))

### Manipulating Tensors

In [16]:
#Addition 
tensor = torch.tensor([5 ,15 , 25])
tensor + 5

tensor([10, 20, 30])

In [17]:
#Simple Multiplication
tensor * 2

tensor([10, 30, 50])

In [18]:
torch.multiply(tensor , 2) #we could also use torch.mul

tensor([10, 30, 50])

In [19]:
torch.add(tensor , 2)

tensor([ 7, 17, 27])

#### Matrix Multiplication (is all you need)

In [20]:
tensor = torch.tensor([2,3,4])
print(tensor * tensor) # simple multiplication
tensor.matmul(tensor) #matrix multiplication

tensor([ 4,  9, 16])


tensor(29)

In [21]:
tensor @ tensor #though not recommended 

tensor(29)

In [22]:
%%time 
#matrix multiplication by hand 

value = 0 
for i in range(len(tensor)):
    value += tensor[i]* tensor[i]

value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(29)

In [23]:
%%time 

#using builtin matrix multiplication 
torch.matmul(tensor , tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(29)

##### Some most common error in deep learning (shape error)

In [24]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) #gives error

In [25]:
tensor_A.T.shape , tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [26]:
torch.mm(tensor_A , tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

##### Finding aggregations.

In [27]:
x = torch.arange(0 , 50 , 5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [28]:
#aggregations
print(f'Minimum: {x.min()}')
print(f'maximum: {x.max()}')
print(f'Meam: {x.type(torch.float32).mean()}')
print(f'Sum {x.sum()}')

Minimum: 0
maximum: 45
Meam: 22.5
Sum 225


In [29]:
#Positional min/max 
tensor = torch.arange(10 , 100 , 10)
print(tensor)
print(f'Index with max value {torch.argmax(tensor)}')
print(f'Index with min value {torch.argmin(tensor)}')

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index with max value 8
Index with min value 0


In [30]:
#Changing Data type 
tensor.dtype

torch.int64

In [31]:
tensor_float32 = tensor.type(torch.float32)
tensor_float32.dtype

torch.float32

Reshaping, stacking, squeezing and unsqueezing

In [32]:
x = torch.arange(1. , 8.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [33]:
x = x.reshape( 1, 7)

In [34]:
y = torch.arange(0. , 10.)
y.reshape(1 ,2 ,5)

tensor([[[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]])

In [35]:
z = y.view(1 , 2,5)
z , z.shape , y , y.shape

(tensor([[[0., 1., 2., 3., 4.],
          [5., 6., 7., 8., 9.]]]),
 torch.Size([1, 2, 5]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([10]))

In [36]:
#changing the view also changes the original tensor 
z[: , 0] = 5
z , y

(tensor([[[5., 5., 5., 5., 5.],
          [5., 6., 7., 8., 9.]]]),
 tensor([5., 5., 5., 5., 5., 5., 6., 7., 8., 9.]))

In [37]:
w = x.view(1 , 7)
w[: , 0] = 5
w , x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]),
 tensor([[5., 2., 3., 4., 5., 6., 7.]]))

In [38]:
## Stacking the  tensors 
x_stacked = torch.stack([x , x ], dim = 0)
x_stacked

tensor([[[5., 2., 3., 4., 5., 6., 7.]],

        [[5., 2., 3., 4., 5., 6., 7.]]])

In [39]:
#Removing Dimensons from Tensor leaving only 1 dimension 
print(f"Previous tensor: {x}")
print(f"Previous Shape: {x.shape}")

#after squeezing 
x_squeezed = x.squeeze()
print(f"The new Tensor : {x_squeezed}")
print(f"New Shape {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous Shape: torch.Size([1, 7])
The new Tensor : tensor([5., 2., 3., 4., 5., 6., 7.])
New Shape torch.Size([7])


In [40]:
#permutaion  
X_original = torch.rand(size = (224 , 224 , 3))

#Permuting the original tensor to rearrange the axis order 
x_permuted = X_original.permute(1 , 2 , 0)

print(f"Previous shape: {X_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([224, 3, 224])


In [41]:
### Indexing (Selecting data from tensors)

x = torch.arange(1 ,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [42]:
#Indexing values foes outer dimension -> inner dimension 
print(f"First square bracket data: {x[0]}")
print(f"Second square bracket data: {x[0][2]}")
print(f"Second square bracket data: {x[0][2][0]}")

First square bracket data: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket data: tensor([7, 8, 9])
Second square bracket data: 7


In [43]:
x[: , 2]

tensor([[7, 8, 9]])

In [44]:
x[: , :, 1]

tensor([[2, 5, 8]])

In [45]:
x[: , :, 2 ]

tensor([[3, 6, 9]])

In [46]:
# Pytorch tensor and Numpy 
import numpy as np 

In [47]:
array = np.arange(1.0 , 8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [48]:
numpyarray = tensor.numpy()
tensor , numpyarray

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [49]:
#Reproducitbility (trying to take the random out of random )
random_tensor_A = torch.rand(3 , 4)
random_tensor_B = torch.rand(3 , 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.0467, 0.2166, 0.6509, 0.1555],
        [0.7853, 0.0344, 0.2144, 0.0315],
        [0.8848, 0.9580, 0.5106, 0.4127]])

Tensor B:
tensor([[0.9150, 0.9952, 0.9148, 0.0924],
        [0.9140, 0.9066, 0.5565, 0.8239],
        [0.4156, 0.4566, 0.2428, 0.1748]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [50]:
#we can make anything reproducible by setting random seed 
import random 
random_seed = 42 #setting the random seed 
torch.manual_seed(seed = random_seed )
random_tensor_C = torch.rand(3 , 4)

#we should call the torch.manual method everytime while creating new tensor 
torch.manual_seed(seed=random_seed )
random_tensor_D = torch.rand(3 , 4)

print(f"Tensor A:\n{random_tensor_C}\n")
print(f"Tensor B:\n{random_tensor_D}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_C == random_tensor_D

Tensor A:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor B:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [51]:
torch.cuda.is_available()

True

In [52]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [53]:
torch.cuda.device_count()

1

In [60]:
##Putting tensors (models) on the GPU 
# torch.cuda.get_device_name() #Getting the name of device 
tensor = torch.tensor([1 , 2,3])
print(tensor , tensor.device)

tensor([1, 2, 3]) cpu


In [61]:
#moving to gpu 
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [65]:
#If the tensor is on gpu we can't transfrom it into nupmy array 
try:
    tensor_on_gpu.numpy()
except:
    tensor_on_gpu = tensor_on_gpu.cpu().numpy()
    print(tensor_on_gpu)

[1 2 3]


In [73]:
torch.cuda.power_draw

<function torch.cuda.power_draw(device: Union[torch.device, str, int, NoneType] = None) -> int>