# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand((7,7))
tensor.shape

torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_2 = torch.rand((1 , 7))
# Perform matrix multiplication 
torch.mm(tensor , tensor_2.T)

tensor([[0.7494],
        [1.2494],
        [1.4017],
        [1.3572],
        [1.3336],
        [1.1400],
        [1.6105]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [18]:
# Set manual seed

torch.manual_seed(0)


# Create two random tensors
tensor_b = torch.rand((7,7))
tenosr_a = torch.rand((1,7))

# Matrix multiply tensors
result = torch.mm(tensor , tensor_2.T) 
result , result.shape

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [19]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [20]:
# Set random seed
seed = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
tensor_1 = torch.rand((2,3)).to(device)
tensor_2 = torch.rand((2,3)).to(device)
print('Device: ' , device)
tensor_1 , tensor_2


Device:  cuda


(tensor([[0.5932, 0.1123, 0.1535],
         [0.2417, 0.7262, 0.7011]], device='cuda:0'),
 tensor([[0.2038, 0.6511, 0.7745],
         [0.4369, 0.5191, 0.6159]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [21]:
# Perform matmul on tensor_A and tensor_B
result = torch.mm(tensor_1 , tensor_2.T)
result

tensor([[0.3129, 0.4120],
        [1.0651, 0.9143]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [10]:
# Find max
print(torch.max(result))
# Find min
print(torch.min(result))

tensor(1.0651, device='cuda:0')
tensor(0.3129, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [12]:
# Find arg max
print(torch.argmax(result))

# Find arg min
print(torch.argmin(result))

tensor(2, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [17]:
# Set seed
torch.manual_seed(7)


# Create random tensor
random_tensor = torch.rand((1,1,1,10))

# Remove single dimensions
modified_tensor = random_tensor.squeeze()

# Print out tensors and their shapes
print(random_tensor , random_tensor.shape)
print(modified_tensor , modified_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


In [22]:
torch.cuda.memory_stats()

OrderedDict([('active.all.allocated', 268),
             ('active.all.current', 11),
             ('active.all.freed', 257),
             ('active.all.peak', 17),
             ('active.large_pool.allocated', 1),
             ('active.large_pool.current', 1),
             ('active.large_pool.freed', 0),
             ('active.large_pool.peak', 1),
             ('active.small_pool.allocated', 267),
             ('active.small_pool.current', 10),
             ('active.small_pool.freed', 257),
             ('active.small_pool.peak', 16),
             ('active_bytes.all.allocated', 8662528),
             ('active_bytes.all.current', 8524800),
             ('active_bytes.all.freed', 137728),
             ('active_bytes.all.peak', 8527872),
             ('active_bytes.large_pool.allocated', 8519680),
             ('active_bytes.large_pool.current', 8519680),
             ('active_bytes.large_pool.freed', 0),
             ('active_bytes.large_pool.peak', 8519680),
             ('active_bytes.sm